var XGManageDes = 
{ 
	s0100:    "On this page, you can query information about the data card in use, specify a network, and set the PIN number for the SIM card.",
	s0101:    "Configure 3G Internet Card",
	s2101:    "Network Connection Configuration",
	s2102:    "You can query the data card version information, and query or specify the network connected using the SIM card.",
	s2103:    "Data Card Name:",
	s2104:    "Data Card Software Version:",
	s2105:    "Data Card Hardware Version:",
	s2106:    "Current Network Connected:",
	s2107:    "Designated Network:",
	s2108:    "2G",
	s2109:    "3G",
	s210a:    "4G",
	s210b:    "AUTO",
	s210c:    "PIN Number Configuration",
	s210d:    "You can query the SIM card status and configure a PIN number for the SIM card.",
	s210e:    "PIN Number Status:",
	s210f:    "Enable PIN number management",
	s2111:    "Disable the PIN number",
	s2112:    "Change the PIN number",
	s2113:    "Delete the locally saved PIN number",
	s2114:    "PUK Code:",
	s2115:    "PIN Number:",
	s2116:    "Old PIN Number:",
	s2117:    "New PIN Number:",
	s2118:    "Confirmation PIN Number:",
	s2119:    "Attempts Available:",
	s211a:    "Please insert a SIM card.",
	s211b:    "The SIM card has been scrapped.",
	s211c:    "The SIM card has been locked. Please enter the correct PUK code to restore the PIN number to unlock the SIM card.",
	s211d:    "Please enter the correct PIN number.",
	s211e:    "The PIN number has been unlocked. You can use the SIM card to surf the Internet. You can also perform the following operations:",
	s211f:    "PIN number management has been disabled.",
	s2120:    "The PIN number should consist of 4 digits. Enter the correct PIN number.",
	s2121:    "The PUK code should consist of 8 digits. Enter the correct PUK code.",
	s2122:    "The confirmation PIN number is different from the new PIN number.",
	s2123:    "Invalid SIM card.",
	s0905:    "The system is busy. Please try later. ",
	s0e08:    "Apply",
    s0e09:    "Cancel"
};
 
﻿
var AccountLgeDes =
{
	s0100:    "On this page, you can change the login password of a common user, set the authentication password of the SSL certificate that is used in device access by HTTPS and import the corresponding SSL certificate.",
	s0101:    "Change Password",
	s0102:    "Account Management",
	s1902:    'The password strength is too weak. Configure it again.',
	s1904:    "The password must consist of 1 to 127 characters.",
	s0f01:    "The password of the common user was changed successfully.",
	s0f02:    "The new password cannot be left blank.",

	s0f04:    "The new password contains invalid characters. Enter a valid one.",
	s0f06:    "The confirm password is different from the new password.",
	s0f07:    "On this page, you can change the password of a common user to ensure security and make it easy to remember.",
	s0f07a:   "On this page, you can change the password of a user to ensure security and make it easy to remember.",
	s0f07b:   "On this page, you can change the login password of a user, set the authentication password of the SSL certificate that is used in device access by HTTPS and import the corresponding SSL certificate.",
	s0f08:    "User Name:",
	s0f09:    "New Password:",
	
	s190a:    "The user name cannot be left blank.",
	s190b:    "The user name must consist of 1 to 31 characters.",
	s1908:    "The user name contains invalid characters. Enter a valid one.",
	s1909:    "User name and password changed successfully.",

	s0f0b:    "Confirm Password:",
	s0f0c:    "Apply",
	s0f0d:    "Cancel",
	s0f0e:    "Password changed successfully.",
	s0f0ea:    "The password is changed successfully. You need to log in again.",
	s0f0f:    "The old password cannot be left blank.",
	s0f11:    "Incorrect old password. Please retry.",
	s0f12:    "On this page, you can change the password of the current login user to ensure security and make it easy to remember.",
	s0f12a:   "On this page, you can change the password of the current login user,set the password for authentication using an SSL certificate for access to the ONT in HTTPS mode, and import the required SSL certificate.",
	s0f13:    "Old Password:",
	s0f14:    "Hint Password:",
	s0f15:    "The password hint cannot be empty.",
	s1116:    "1.The password must contain at least 6 characters.<br/>2.The password must contain at least two of the following combinations: <br/>&nbsp;&nbsp;&nbsp;Digit, uppercase letter, lowercase letter <br/>&nbsp;&nbsp;&nbsp;Special characters (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.The password cannot be any user name or user name in reverse order.",
	s1116a:   "1.The password must contain at least 6 characters.<br/>2.The password must contain at least two of the following combinations: <br/>&nbsp;&nbsp;&nbsp;Digit, uppercase letter, lowercase letter <br/>&nbsp;&nbsp;&nbsp;Special characters (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.The password cannot be any user name or user name in reverse order.",
	ss1116b:  "1.It is recommended that the password consist of at least six characters.<br/>2. It is suggested that at least two types of the following characters be included in the password: digits, uppercase characters, lowercase characters, and special characters. Special characters can be the following: `~!@#$%^&*()-_=+|[{}];:'&lt;,.&gt;/?<br/>3. It is suggested that the password be not the username or the username in reverse order.",
	ss1116c:  "1.It is recommended that the password consist of at least six characters.<br/>2. It is suggested that at least two types of the following characters be included in the password: digits, uppercase characters, lowercase characters, and underscores (_).<br/>3. It is suggested that the password be not the username or the username in reverse order.",
	ss1116d:    "1.The password must contain at least 8 characters.<br/>2.The password must contain at least two of the following combinations: <br/>&nbsp;&nbsp;&nbsp;Digit, uppercase letter, lowercase letter <br/>&nbsp;&nbsp;&nbsp;Special characters (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.The password cannot be any user name or user name in reverse order.",
	ss1116e:   "1.The password must contain at least 5 characters.<br/>2.The password must contain at least two of the following combinations: <br/>&nbsp;&nbsp;&nbsp;Digit, uppercase letter, lowercase letter <br/>&nbsp;&nbsp;&nbsp;Special characters (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.The password cannot be any user name or user name in reverse order.",
	
	s1117:    "The password is weak. Are you sure you want to continue?",
	s1118:    "<strong class=\"color_red\">The login password is the default one. Change it immediately.</strong>",

	s1119:    "ONT Management",
	s1119lan: "Smart Gateway Management",
	s1120:    "Change Management Password",
	s1121:    "Save",
	s1122:    "Reset and Restore Configuration",
	s1123:    "Restart",
	s1124:    "Restore Defaults",
	s1125:    "Click it to restart the device.",
	s1126:    "Click it to restore the terminal device to its default configurations.",
	s1127:    "Restore Defaults",

	s0d21:    "Apply",
	s0d22:    "Cancel",

	s0d23:    "Enable Certificate Authentication and Set Private Key Password",

	s0d25:    "Enable Certificate Authentication:",
	s0d26:    "Private Key Password:",
	s0d28:    "Confirm Password:",
	s0d29:    "Import Certificate",
	s0d2a:    "Certificate:",
	s0d2b:    "Browse…",
	s0d2c:    "Import Certificate",
	s0d10:    "Select a file path.",
	s0d11:    "The file path length cannot exceed 128 characters.",
	s0d0f:    "The confirm password is different from the private key password.",
	s0d14:    "Successfully changed the private key password. It takes effect after a device restart.",
	s1430:    "The password cannot be blank. Please retry.",
	s1901:    "On this page, you can set the SSL authentication password used for accessing an ONT using HTTPS and import the corresponding SSL certificate. ",
	s1902:    "The password strength is too weak. Configure it again.",
	s1903:    "SSL Certificate Management",
	s1904:    "The password must consist of 1 to 127 characters.",
	s1905:    "(1–127 characters. This password takes effect after a device restart.)",

	s2000:    "Please change your login password!",
	s2001:    "Previous",
	s2002:    "Next",
	s2003:    "Skip",
	s2004:    "Exit",

	s2010:    "Password requirements",
	s2011:    "The password must contain at least 6 characters.",
	ss2011a:   "The password must contain at least 8 characters.",
	s2012:    "The password must contain at least two of the following combinations:Digit, uppercase letter, lowercase letter and Special characters (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).",
	s2013:    "The password cannot be any user name or user name in reverse order.",
	
	s2201: "Router password change",
	s2202: "You can change the router access password here. The password should contain at least 8 alphanumeric characters:",
	s2203: "Old password:",
	s2204: "New password:",
	s2205: "Confirm new password:",
	s2206: "Password strength",
	s2207: "Your password has been changed.",

	s2208: "Close",
	s2209: "OK",
	s220a: "Cancel",

	s220b: "Low",
	s220c: "Medium",
	s220d: "High",
	
	s2300: "Account settings",
	s2301: "Modify the password of your Vivo Box, typing the current password once and your new password twice.<br>We suggest that you write down your new password after you change it. ",
	s2302: "Current Password:",
	s2303: "New Password:",
	s2304: "(confirm)",
	s2305: "Save",
	s2306: "Cancel"
};
 
﻿
var ApmcfgLgeDes = 
{ 
	s0100: 	  "Advanced Power Management",
    s0e01:    "On this page, you can set energy saving for the device.",
    s0e02:    "Energy Saving Configuration",
    s0e03:    "Enable Energy Saving:",
    s0e04:    "Enable Services in Battery Mode",
    s0e05:    "Service",
    s0e06:    "Enable",
    s0e07:    "Remote Management:",
    s0e08:    "Apply",
    s0e09:    "Cancel",
    s0e0a:    "VOICE:"
};
 
﻿
var BatteryinfoLgeDes = 
{ 
    s0101:    "On this page, you can view the power supply mode and the available battery capacity.",
    s0102:    "Power Supply Mode:",
    s0103:    "Battery",
    s0104:    "Commercial power",
    s0105:    "Available Battery Capacity:"
};
 
﻿
var BssLgeDes = 
{
	s0100:	  "Service Provisioning Status",	
	s1300:    "On this page, you can query the service provisioning status.",
	s1301:    "ONT  Registration Status:",
	s1301a:    "ONR  Registration Status:",
	s1302:    "--",
	s1303:    "The ONT is registering with the OLT. Please wait.",
	s1303a:    "The ONR is registering with the OLT. Please wait.",
	s1304:    "Successfully registered the ONT with the OLT.",
	s1304a:    "Successfully registered the ONR with the OLT.",
	s1305:    "Refresh",
	s1306:    "Registration with the OLT timed out. The possible causes are as follows: <br/>1. The optical fiber is not connected or the optical power is abnormal. <br/> 2. The PON authentication information is incorrect. <br/>If the above-mentioned information is correct, contact the customer service center.",
	s1307:    "OLT Service Configuration Status:",
	s1308:    "The OLT is applying configurations. Please wait.",
	s1309:    "OLT service configured successfully. ",
	s130a:    "Failed to configure the OLT service. ",
	s130b:    "Failed to obtain the status because the OLT version does not match.",
	s130c:    "EMS Configuration Status:",
	s130d:    "No XML configurations applied.",
	s130e:    "The EMS is applying configurations.",
	s130f:    "EMS service configured successfully.",
	s1310:    "Failed to configure the EMS service.",
	s1311:    "ACS Registration Status:",
	s1312:    "The ONT is waiting to be registered with the ACS server. Please wait.",
	s1312a:    "The ONR is waiting to be registered with the ACS server. Please wait.",
	s1313:    "The ONT is registering with the ACS server. Please wait.",
	s1313a:    "The ONR is registering with the ACS server. Please wait.",
	s1314:    "Successfully registered with the ACS server.",
	s1315:    "Failed to register with the ACS server.",
	s1316:    "ONT is not compatible with OLT. Please replace the ONT.",
	s1316a:    "ONR is not compatible with OLT. Please replace the ONR.",
	s1317:    "Obtaining the status. Please wait.",
	
	s2000:"Configuration is completed. Issuing services...",
	s2001:"Return to Home Page",
	s2002:"The ONT is registering with the OLT... Please wait.",
	s2002a:"The ONR is registering with the OLT... Please wait.",
	s2003:"Service successfully issued. Welcome.",
	s2004:"The EMS is issuing configurations...Please wait.",
	s2005:"Service configuration on the EMS failed. Verify EMS settings.",
	s2006:"Successfully registered with the ACS.",
	s2007:"The ONT is registering with the ACS server... Please wait.",
	s2007a:"The ONR is registering with the ACS server... Please wait.",
	s2008:"The ONT failed to register with the ACS.",
	s2008a:"The ONR failed to register with the ACS.",
	s2009:"The ONT registration with the OLT timed out. Possible causes: <br/>1. A fiber is not connected or optical power is abnormal. <br/>2. PON authentication information is incorrect. <br/>If no abnormality is found, contact Huawei.",
	s2009a:"The ONR registration with the OLT timed out. Possible causes: <br/>1. A fiber is not connected or optical power is abnormal. <br/>2. PON authentication information is incorrect. <br/>If no abnormality is found, contact Huawei.",
	s2010:"Service configuration on the OLT failed.",
	s2011:"The OLT is issuing configurations... Please wait.",
	s2012:"Failed to obtain the state because the OLT version does not match.",
	s2013:"Service provisioning is incomplete. Navigate to the home page, and click the Service Provisioning Status tab on the left side of the page to view service provisioning information."
};
 
﻿
var CfgfileLgeDes = 
{ 
	s0100:    "On this page, you can store, download, and update the configuration file.",
	s0101:    "Save Configurations and Reset",
	s0102:    "Configuration File Management",
	s0905:    "The system is busy. Please try later. ",
    s0701:    "Configuration file saved successfully.",
    s0702:    "The file path cannot be left blank.",
    s0703:    "The path length cannot exceed 128 characters.",
    s0704:    "The file is too large.",
    s0705:    "The file is invalid or does not exist.",
    s0706:    "Are you sure you want to save configurations and restart the terminal?",
    s0707:    "On this page, you can store the configuration file.",
    s0709:    "Save",
    s070a:    "Save and Restart",
    s070b:    "You can download the current configuration file to the local computer.",
    s070c:    "Download Configuration File",
    s070d:    "If you enter the path of the configuration file and click Update Configuration File, your terminal will be updated with the saved configuration file.",
    s070e:    "Configuration File:",
    s070f:    "Browse…",
    s0710:    "Update Configuration File",
	s0711:	  "If you import the configuration file, your terminal will restart and the imported configuration file will take effect. Are you sure you want to continue?",
	
	s0a01:    "If you restore the default settings, user-defined data will be lost and the device will restart. Are you sure you want to continue?",
    s0a02:    "On this page, you can restore the default settings.",
    s0a03:    "Default"
};
 
﻿
var CfgguideLgeDes = 
{ 
	s1116:    "1.The password must contain at least 6 characters.<br/>2.The password must contain at least two of the following combinations: <br/>&nbsp;&nbsp;&nbsp;Digit, uppercase letter, lowercase letter <br/>&nbsp;&nbsp;&nbsp;Special characters (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.The password cannot be any user name or user name in reverse order.",
	s1116a:   "1.The password must contain at least 6 characters.<br/>2.The password must contain at least two of the following combinations: <br/>&nbsp;&nbsp;&nbsp;Digit, uppercase letter, lowercase letter <br/>&nbsp;&nbsp;&nbsp;Special characters (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.The password cannot be the user name or the user name in reverse order.",
	s0f0f:    "The old password cannot be left blank.",
	s0f02:    "The new password cannot be left blank.",
	s0f04:    "The new password contains invalid characters. Enter a valid one.",
	s0f06:    "The confirm password is different from the new password.",
	s0f08:    "User Name:",
	s0f09:    "New Password:",
	s0f0b:    "Confirm Password:",
	s0f11:    "Incorrect old password. Please retry.",
	s0f13:    "Old Password:",
	s1902:	  'The password strength is too weak. Configure it again.',
	s1904:    "The password must consist of 1 to 127 characters.",
	
	s2000:    	"Service Provisioning Method",
	s2001:    	"On the OLT",
	s2002:    	"Services for the ONT are configured on the OLT.",
	s2003:    	"On the EMS",
	s2004:    	"Services for the ONT are configured on the EMS.",
	s2005:    	"On the ACS",
	s2006:    	"Services for the ONT are configured on the ACS.",
	s2007:    	"On the ONT web page",
	s2008:    	"Services for the ONT are configured on the ONT web page.",
	s2009:    	"Exit",
	s2010:    	"Next",
	s2011:    	"Copyright © Huawei Technologies Co., Ltd 2009-2017. All rights reserved.",
	
	s2012:    	"Welcome to Huawei ONT for connecting you to your family and friends.",
	s2012lan:   "Welcome to Huawei smart gateway for connecting you to your family and friends.",
	s2012SINGTEL:"Welcome to Singtel Optical Network Router!",
	s2012SINGTELHS:"Welcome to Optical Network Router!",
	s2013:    	"ONT authentication",
	s2014:    	"WAN configuration",
	s2015:    	"Configuration completion",
	
	s2016:    	"Internet configuration",
	s2017:    	"Wi-Fi configuration",
	s2018:    	"Account management",
	
	s2019:    	"Configuration is completed. Welcome!",
	s2020:    	"Previous",
	s2021:    	"Return to Home Page",
	
	s2040:      "Current network connection mode: ",
	s2041:      "Wired",
	s2042:      "Wi-Fi",
	s2043:      "If you have modified Wi-Fi parameters, try the connection again.",
	s2044:      "You can navigate to the home page and start using the ONT.",
	s2044lan:    "You can navigate to the home page and start using the smart gateway.",
	
	s0601:    "Unsaved data will be lost. Are you sure you want to restart the device?",
	s030e:    "Configuration succeeded",

    s3001:    "PLOAM password should be 10 digits."
};

var RosWizardDes =
{
	s0100:    "enter PLOAM-password",
	s0101:    "PLOAM-code",
	s0102:    "Continue",
	s1100:    "New password",
	s1101:    "confirm",
	s1102:	  'The password strength is too weak. Configure it again.',
	s1200:    "Device connect with optical network GPON",
	s1201:    "Start the wizard ",
	s1202:    "Configure the device manully",
	s3101:    "You can change name and password for your Wi-Fi networkin this window. You can also turn off Wi-Fi? If necessary.",
	s3102:    "Enable wireless 2.4 GHz",
	s3103:    "Wireless network name",
	s3104:    "Wireless network password",
	s3105:    "Enable wireless 5.0 GHz",
	s3106:    "Wireless network name ",
	s3107:    "Wireless network password ",
	s3108:    "Back",
	s4100:    "Start work in Internet",
	s4101:    "Go to the Rostelecom webside",
	s4110:    "Made the connection setup",
	s4111a:   "Please waiting",
	s4111b:   "second",
	s4112:    "Don’t remove the device’s power",
	s4113:    "Continue to work in Internet",	
	s4200:    "The device was unable to establish a connection to the Internet. For further customize go to Web-interface and configure services manually",
	s4201:    "Go to Web-interface",
	s4202:	  "Automatic setup fails", 	
	s5100:    "Please check the connection  WAN Cable, show on the photo below.",
	s5101:    "No optical connection",
	s5200:    "The device cannot connect to the Rostelecom network. Please, contact technical support by phone 8-800-",
	s5201:    "Device version",
	s5202:    "Software version ",
	s5203:    "MАС address PPPoE connection",
	s5204:    "Output signal dBm",
	s5205:    "Device model",
	s5206:    "Service information",
	s5207:    "Serial number GPON",
	s5208:    "Status  OMCI",
	s5209:    "Wizard",
	s5210:    "Cannot connect to the Rostelecom network"
};
 
﻿
var CollectInfoLgeDes = 
{ 
	s1101:    "Enable Collect fault information",
    s1102:    "On this page, you can collect and download fault information.",
	s1104:	  "Start",
	s1114:    "Download",
	s1119:    "Collecting the fault information...Please wait.",
	s1120:    "Fault information collected successfully."
};
 
﻿
var DebuglogviewLgeDes = 
{ 
	s0100:    "On this page, you can download and query debug logs.",
	s0101:    "Debug Log",
    s0b0f:    "Download and View Logs",
    s0b10:    "You can view logs and download log files.",
    s0b11:    "Download Log File"
};
 
﻿var DevInfoDes = 
{ 
	s0200:    "Device Information",
    s0201:    "On this page, you can view basic device information.",
    s0202:    "Device Type:",
    s0203:    "Description:",
    s0204:    "Hardware Version:",
    s0205:    "Software Version:",
    s0206:    "ONT Registration Status:",
	s0206a:    "ONR Registration Status:",
    s0207:    "ONT ID:",
	s0207a:    "ONR ID:",
    s0208:    "CPU Usage:",
    s0209:    "Memory Usage:",
    s020a:    "XML Alias:",
	s020b:    "Unregistered and unauthorized",
	s020c:    "Registered and authorized",
	s020d:    "Registered but unauthorized",
	s020e:	  "Device Runtime:",
	s020f:    " day ",
	s0210:    " hour ",
	s0211:    " minute ",
	s0212:    " second",
	s0213:    " days ",
	s0214:    " hours ",
	s0215:    " minutes ",
	s0216:    " seconds ",
 	s0217:    "Manufacture Info:",
	s021a:    "Uptime:",
	s0225:    "Custom Info:",
	s0226:    "System Time:",
	s0229:    "PPP Online Duration (dd:hh:mm:ss):",	
	s1321:    "ONT is not compatible with OLT. Please replace the ONT.",
	s1321a:    "ONR is not compatible with OLT. Please replace the ONR.",
	s1322:    "(Initial state)",
	s1323:    "(Standby state)",
	s1324:    "(Serial-Number state)",
	s1325:    "(Ranging state)",
	s1326:    "(Operation state)",
	s1327:    "(POPUP state)",
	s1328:    "(Emergency-Stop state)",
	s1611:    "SN:",
	s1612:    "Mac:&nbsp;",
	s1613:    "IMEI:",
	s2016:    "The administrator uses the initial password. If you want to change this password, please contact the telecom carrier. For details about how to change the password, see the Security Maintenance from http://support.huawei.com."
};
 
﻿
var DlnaLgeDes =
{
	s0526:"Apply",
	s0527:"Cancel",
	s0531:"Caution:",
	s0532:"Do not remove and re-insert the USB storage device in use, because this may damage files in it.",
	s1410:"Share path:",
	s1436:"Browse Directory",
	s1600:"In the media sharing service, you can share media information to devices that support DLNA. For example, you can share video, audio, and pictures to PCs, mobile devices, and consumption appliances. On this page, you can configure the sharing service switch and share directories.",
	s1601:"Enable media sharing:",
	s1602:"Share path:",
	s1603:"All paths",
	s1604:"Specify path",
	s1605:"Browse...",
	s1606:"A maximum of 10 share paths can be configured.",
	s1607:"The path cannot be blank. Please specify a path.",
	s1608:"The path is already in the list. Please specify another one.",
	s1609:"Specified path:",
	s1610:"The length of the specified path exceeds the upper limit.",
	s1611:"Media Sharing"
};
 

var FirmwareLgeDes = 
{ 
	s0900:	  "Software Upgrade",
    s0901:    "Select a firmware file.",
    s0902:    "The path length of the firmware file cannot exceed 128 characters.",
    s0903:    "The firmware is too large.",
    s0905:    "The system is busy. Please try later. ",
    s0906:    "On this page, you can use the firmware upgrade function to upgrade the software of the terminal to the target version.",
	s0906a:   "On this page, you can use version file upgrade to upgrade the software version of the terminal to your expected version. If you enable automatic upgrade, the terminal automatically updates the firmware version from the remote server. ",
    s0907:    "Firmware file:",
    s0908:    "Browse... ",
    s0909:    "Upgrade",
	s090a:    "Automatic Upgrade Configuration",
	s090b:    "Local Upgrade",
	s090c:    "Enable automatic upgrade"
};

 
﻿var LanguageLgedes =
{
	s001:	"Language",
	s002:	"Choose the language of the Vivo Box user interface:",
	s003:	"Portugues",
	s004:	"English",
	s005:	"Cancel",
	s006:	"Save"
}; 
﻿
var LedcfgLgeDes = 
{ 
	s0100: 	  "Indicator Status Management", 
    s0e08:    "Apply",
    s0e09:    "Cancel",
	s1500:	  "On this page, you can set the indicator switch of a device. You can configure an indicator off period if you set Indicator switch to Off. An indicator is always off if you do not specify an indicator off period.",
	s1501:    "Indicator Switch Configuration",
	s1801:    "Start time",
	s1802:    "End time",
	s1803:    "Indicator Switch",
	s1804:    "Indicator Off Period",
	s1805:    ":",
	s1806:    "(00:00-23:59)",
	s1807:	  'The number of periods configured reaches the allowed upper limit. You are not allowed to add a new one.',
	s1808:    "On",
	s1809:	  'Off',
	s1810:	  'Invalid start time.',
	s1811:	  'Invalid end time.',
	s1812:	  'The hour you entered is invalid. Please enter a value ranging from 00 to 23.',
	s1813:	  'The minute you entered is invalid. Please enter a value ranging from 00 to 59.',
	s1814:	  'The period you specified is invalid. The start time must be earlier than the end time. ',
	s1815:	  'No period rule is configured.',
	s1816:	  'Please select a period.',
	s1817:	  'The period you specified overlaps a previously configured period. Please specify another period.',
	s1818:	  'Indicator Off Period Configuration'

};
 
var PrompterDes = 
{ 
	s1005:    "Upgrade failed. Select the correct file and retry. Note: The device cannot be upgraded if the type of the selected file is incorrect.",
	s1010:    "Restart",
	s1012:    "Failed to update the configuration file. Select the correct file and retry.",
	s1015:    "Retry",
	s1316:    "Failed to back up the configuration file to the USB device.",
	s1317:    "Successfully backed up the configuration file to the USB device.",
	s1318:    "Failed to import the certificate. Select the correct file, and try again.",
	s1319:    "Certificate imported successfully.",
	s131a:    "Successfully updated the configuration file. The system is restarting. Please wait.",
	s131b:    "File download failed. The possible causes are as follows:<br>1. The file does not exist.<br>2. Parameters are incorrectly set.<br>3. The system is busy.",
	s131c:    "Failed to restore the default configurations.",
	s131d:    "Successfully restored the configuration. The system is restarting. Please wait.",
	s131e:    "The current configuration in the device is the same as the default configuration.",
	s131f:    "Upgrade succeeded. Click the button to restart the device and activate the file.",
	s1320:    "Are you sure you want to restart the device?",
	s1321:    "Notice: Login failed because the number of login users exceeds the upper threshold or the user has already logged in."
};
 
﻿var SmartDiagnoseLgeDes = 
{
	s1900:    	'Internet connection is abnormal',
	s1900a:    	'Internet connection is unavailable',
	s1901:      'RF module chip fault.',
	s1902:      'DECT chip fault',
	s2000:	    'SD5113 chip fault.',
	s2001:      'Wi-Fi chip fault.',
	s2002:		'LSW chip fault.',
	s2003:		'Codec chip fault.',
	s2004:		'Optical module chip fault.',
	s2005:		'PHY chip fault.',
	s2006:		'MAC chip forwarding is abnormal; ',
	s2006a:		'MAC chip forwarding is unavailable; ',
	s2007:		'PHY chip forwarding is abnormal; ',
	s2007a:		'PHY chip forwarding is unavailable; ',
	s2008:		'Hardware is normal',
	s2008lan:		'Hardware is normal',
	s2008a:		'ONR hardware is normal',
	s2009:		'Hardware is abnormal',
	s2009lan:		'Hardware is abnormal',
	s2009a:		'ONR hardware is abnormal',
	s2009b:		'ONR hardware is unavailable',
	s2010:    	'Internet connection is normal',
	s2011:    	'PPPoE dialup failed.',
	s2012:    	'DHCP dialup failed',
	s2013:    	'Internet connection status',
	s2014:    	'Hardware status',
	s2014lan:   'Hardware status',
	s2014a:    	'ONR hardware status',
	
	s2015:    	'One-Click Diagnosis',	
	s2016:    	'Diagnosing...',
	s2017:    	'The diagnosis result is normal.',	
	s2018:    	'The diagnosis result is abnormal. Handle the abnormality!',	
	s2018a:    	'The diagnosis result is service unavailable.',	
	s2019:    	'Diagnose again',	
	s2020:    	'Password strength',	
	s2021:    	'User password strength',
	s2022:    	'Low',
	s2023:    	'High',	
	s2024:    	'Wi-Fi password strength',
	s2025:      'The optical path is normal.',
	s2026:      'This optical path is abnormal. Check optical fiber connections.',
	s2026a:     'This optical path is unavailable. Check optical fiber connections.',
	s2027:      'Registration with the OLT succeeded.',
	s2028:      'Registration with the OLT failed. Check registration parameters.',
	s2029:      'This diagnosis method applies for only a professional engineer and it affects data services. Therefore, exercise caution when you use this diagnosis method. ',
	s2029pwd:      'System Tools',
	s2029pwdc:     'Modify Login Password',	
	s2029wifi:      'WLAN',
	s2029wific:     'WLAN Basic Configuration',		
	
	s3000:      'Voice service status',
	s3001:      'Voice service is normal',
	s3002:      'Port',
	s3003:      'Testing...',
	s3004:      'No voice service configured',
	s3005:      'Voice service closed',
	s3006:      'Registration failed',
	s3007:      'Loop test result is abnormal',
	s3007a:     'Loop test result is unavailable',
	s3008:      'Voice network connection is abnormal',
	s3008a:     'Voice network connection is unavailable',
	s3009:      'unknown error',
	s3010:      'The loop test is not implemented because other ports are in calls',
	s3011:      'The SD card is normal',
	s3012:      'The SD card is not detected',
	s3013:      'The SD card is abnormal',
	
	s3014: 		'Status of the gateway IPTV service',
	s3015: 		'The built-in STB port is normal',
	s3016: 		'The built-in STB port is abnormal. Contact the carrier for assistance.  ',
	s3017: 		'IPTV configurations are normal',
	s3018: 		'IPTV configurations of the gateway are incorrect. Check WAN port configurations.  ',
	s3019: 		'The IPTV network of the gateway is normal.',
	s3020: 		'The IPTV network of the gateway is abnormal. Check the connection status of the WAN port.  ',
	s3021: 		'The IPTV service of the gateway is normal. ',
	s3022: 		'The built-in STB has no traffic. ',
	s3023:      'The PPPoE dialup mode is manual. Please perform dialup manually.'

};
 
﻿var ResetLgeDes = 
{  
    s0601:    "Unsaved data will be lost. Are you sure you want to restart the device?",
    s0602:    "On this page, you can restart the device.",
    s0603:    "Restart",
	s0604:    "Are you sure you wanto to reboot the Vivo Box? \r\n Your internet services, telephony and TV may be interrupted momentarily while the Vivo Box reestablishes the connection. The process can take up to 5 minutes and will automatically return.",
	
	s0701:	"Options",
	s0702:	"Reboot",
	s0703:	"This button will reboot the Vivo Box. When you click here, your Internet, telephone and TV may not be available until the inicialization has finished. All the Vivo Box configuration will be preserved.",
	s0704:	"Reconfigure",
	s0705:	"This button will reconfigure the Vivo Box. When you click here, your Internet, telephone and TV may not be available until the inicialization has finished. All the Vivo Box configuration will be lost, including the customized name of your Wi-Fi network and the password.",
	s0706:	"If you restore the default settings, user-defined data will be lost and the device will restart. Are you sure you want to continue?",
	s0707:	"Are you sure you want to reconfigure the Vivo Box? \r\n All customization will be lost, including the name and password of your Wi-Fi network."

};
 
﻿var RestoreLgeDes = 
{
    s0a01:    "If you restore the default settings, user-defined data will be lost and the device will restart. Are you sure you want to continue?",
    s0a02:    "On this page, you can restore the default settings.",
    s0a03:    "Default",
	s0a04:	  "Do you want to reset IoT configurations? If yes, you need to reinstall sensors one by one.",
	s0a05:	  "Reset IoT configurations",
	s0a06:	  "Apply",
	s0a07:	  "Cancel",
	s0a08:    "On this page, you can restore default configurations and factory defaults. The ftth id will be deleted when you restore factory defaults.",
	s0a09:    "If you restore the factory defaults, user-defined data and ftth id will be lost and the device will restart. Are you sure you want to continue?",
	s0a0a:    "Restore factory defaults"

};
 
﻿var AcsstatusLgeDes = 
{
	s0100:    "Remote Manage",
    s0301:    "On this page, you can view the remote-connection status and service provisioning status.",
    s0302:    "Unsolicited Report Status:",
    s0303:    "Succeeded",
    s0304:    "Not reported",
    s0305:    "No response",
    s0306:    "Interrupted",
    s0307:    "Unknown",
    s0308:    "ACS Connection Status:",
    s0309:    "Remote connection succeeded",
    s030a:    "No remote connection request",
    s030b:    "Remote connection interrupted",
    s030c:    "Service Provisioning Status:",
    s030d:    "Remote service configuration being received",
    s030e:    "Configuration succeeded",
    s030f:    "Configuration failed",
    s0310:    "Remote service configuration not applied"

};
 
﻿var SambaLgeDes =
{
	ss1116b:    "1.It is recommended that the password consist of at least six characters.<br/>2. It is suggested that at least two types of the following characters be included in the password: digits, uppercase characters, lowercase characters, and special characters. Special characters can be the following: `~!@#$%^&*()-_=+|[{}];:'&lt;,.&gt;/?<br/>3. It is suggested that the password be not the username or the username in reverse order.",
	ss1116c:    "1.It is recommended that the password consist of at least six characters.<br/>2. It is suggested that at least two types of the following characters be included in the password: digits, uppercase characters, lowercase characters, and underscores (_).<br/>3. It is suggested that the password be not the username or the username in reverse order.",
	s0526:      "Apply",
	s0527:      "Cancel",
	s0531:      "Caution:",
	s0532:      "Do not remove and re-insert the USB storage device in use, because this may damage files in it.",
	s1400:      "On this page, you can enable the home printer and storage sharing.<br/>Before enabling the home printer, connect the printer to the home gateway through a USB port. The printer and home gateway shares one IP address. Scan for the printer and install the drive. Then you can use the printer.",
	s1401:      "Enable printer and storage sharing:",
	s1402:      "Home printer information:",
	s1403:      "Enable sharing authentication:",
	s1404:      "Account Settings",
	s1405:      "Details",
	s1406:      "Username:",
	s1407:      "Password:",
	s1408:      "Enable:",
	s1409:      "Permission:",
	s1410:      "Share path:",
	s1411:      "Directory:",
	s1412:      "Are you sure you want to delete the user?",
	s1413:      "ID",
	s1414:      "Username",
	s1415:      "State",
	s1416:      "Permission",
	s1417:      "Shared Path",
	s1418:      "Enable",
	s1419:      "Disable",
	s1420:      "Read-only",
	s1421:      "Read-write",
	s1422:      "Hide",
	s1423:      "All paths",
	s1424:      "Specify path",
	s1425:      "Browse",
	s1426:      "The username cannot be blank. Please retry.",
	s1427:      "The username cannot be a special username used by the system or a process name. Please retry.",
	s1428:      "The username already exists. Please retry.",
	s1429:      "Invalid user name. A user name can contain only lower-case letters, digits, and underscores. ",
	s1430:      "The password cannot be blank. Please retry.",
	s1431:      "The path of the storage service user cannot be blank.",
	s1432:      "A maximum of 8 users can be configured.",
	s1433:      "USB Storage Devices:",
	s1434:      "Back",
	s1435:      "OK",
	s1436:      "Browse Directory",
	s1437:      "Invalid password. Please retry.",
	s1438:      "A username cannot start with a digit. Please retry.",
	s1439:      "The password is weak. Continue?",
	s1440:      "A password contains only letters, digits, and underscores (_).",
	s1441:      "The path length exceeds the limit.",
	s1442:      "Low password security. Enter a password again.",
	s1443:      "The equipment logic plate district ID gain contains errors, please after renovating the page, retries!",
	s1444:      "USB Home Sharing",
	s1445:      "Home Sharing"
};
 
﻿var SmartOntdes =
{
	smart001:"PON info",
	smart002:"Connection status:",
	smart003:"Connected",
	smart004:"Disconnected",
	smart005:"Connection duration:",
	smart006:"h",
	smart007:"min",
	smart008:"s",
	smart009:"Registration status",
	smart010:"Optical path (OLT):",
	smart011:"Unauthenticated",
	smart012:"Authentication succeeded",
	smart013:"Authentication failed",
	smart014:"Registration status (ACS):",
	smart015:"Unregistered",
	smart016:"Registration succeeded",
	smart017:"Registration failed",
	smart018:"Network connection status",
	smart019:"IP Protocol:",
	smart020:"IP Address:",
	smart021:"Line protocol:",
	smart022:"Succeeded",
	smart023:"Not reported",
	smart024:"No response",
	smart025:"Interrupted",
	smart026:"Unknown",
	smart027:"IPv4 Address:",
	smart028:"IPv6 Address:",
	smart029:"The fiber is disconnected.",

	smart030:    "On this page, you can use the bundle load function to load the bundle file.", 
	smart030lan: "bundle load",
	smart031:    "Bundle file:",
	smart032:    "Browse... ",
	smart033:    "Load",
	smart034:    "On this page, You can query and operate bundle information.",
	smart034lan: "Bundle Configuration",
	smart034B:   "On this page, You can query bundle information.",
	smart035:    "Bundle Information",
	smart036:    "ID",
	smart037:    "Status",
	smart038:    "Name",
	smart039:    "Version",
	smart040:    "Update",
	smart041:    "Start",
	smart042:    "Stop",
	smart043:    "Delete",

	s0702:    "The file path cannot be left blank.",
	s0703:    "The path length cannot exceed 128 characters.",
	s0905:    "The system is busy. Please try later. ",
	s1118:    '<strong class="color_red1">The login password is the default one. Change it immediately.</strong>',
	s1119:    "Collecting the fault information...Please wait."
}; 
﻿var SntpLgeDes =
{
	s0c01: "The time synchronization period must be greater than 0.",
	s0c02: "Invalid time synchronization period.",
	s0c03: "The second text box for the primary SNTP server cannot be left blank when Other is selected in the first text box.",
	s0c04: "Incorrect IP address format of the primary SNTP server.",
	s0c05: "Invalid IP address of the primary SNTP server. Enter a unicast address.",
	s0c06: "Invalid address of the primary SNTP server.",
	s0c07: "The second text box for the secondary SNTP server cannot be left blank when Other is selected in the first text box.",
	s0c08: "Incorrect IP address format of the secondary SNTP server.",
	s0c09: "Invalid IP address of the secondary SNTP server. Enter a unicast address.",
	s0c0a: "Invalid address of the secondary SNTP server.",
	s0c0b: "Time zone changes take effect only after the device is restarted.",
	s0c0c: "DST settings cannot be empty.",
	s0c0d: "Incorrect time format.",
	s0c0e: "Both the start and end time must be specified.",
	s0c0f: "On this page, you can configure the SNTP protocol, time zone, and DST to obtain the accurate time.",
	s0c10: "Automatically synchronize the network time server",
	s0c11: "Primary SNTP Server:",
	s0c12: "Secondary SNTP Server:",
	s0c13: "Time Zone:",
	s0c14: "Time Synchronization Period:",
	s0c15: " (s)",
	s0c16: "WAN Name:",
	s0c17: "Apply",
	s0c18: "Cancel",
	s0c19: "Enable DST",
	s0c1a: "DST Start Time:",
	s0c1b: "January",
	s0c1c: "February",
	s0c1d: "March",
	s0c1e: "April",
	s0c1f: "May",
	s0c20: "June",
	s0c21: "July",
	s0c22: "August",
	s0c23: "September",
	s0c24: "October",
	s0c25: "November",
	s0c26: "December",
	s0c27: "First",
	s0c28: "Second",
	s0c29: "Third",
	s0c2a: "Fourth",
	s0c2b: "Last",
	s0c2c: "Sunday",
	s0c2d: "Monday",
	s0c2e: "Tuesday",
	s0c2f: "Wednesday",
	s0c30: "Thursday",
	s0c31: "Friday",
	s0c32: "Saturday",
	s0c33: "Hour:",
	s0c34: "",
	s0c35: "Minute:",
	s0c36: "",
	s0c37: "Second:",
	s0c38: "",
	s0c39: "DST End Time:",
	s0c40: "Current Time:",
	s0c41: "The start and end dates for the DST cannot be in the same month.",
	s0c42: "Whether to Validate Customized Time Segments",
	s0c43: "Day",
	s0c44: "Time Segment",
	s0c45: "Global indicator disabling time segment",
	s0c46: "Yes",
	s0c47: "Customized indicator disabling time segment",
	s0c48: "Disable the indicator",
	s0c49: "Time Setting",
	s0c4a: "The second text box for the tertiary SNTP server cannot be left blank when Other is selected in the first text box.",
	s0c4b: "Incorrect IP address format of the tertiary SNTP server.",
	s0c4c: "Invalid IP address of the tertiary SNTP server. Enter a unicast address.",
	s0c4d: "Invalid address of the tertiary SNTP server.",
	s0c4e: "The second text box for the quaternary SNTP server cannot be left blank when Other is selected in the first text box.",
	s0c4f: "Incorrect IP address format of the quaternary SNTP server.",
	s0c50: "Invalid IP address of the quaternary SNTP server. Enter a unicast address.",
	s0c51: "Invalid address of the quaternary SNTP server.",
	s0c52: "Tertiary SNTP Server:",
	s0c53: "Quaternary SNTP Server:",
	s0c54: "Notice:",
	s0c55: "Incorrect configurations may affect services related to time. Therefore, you are advised to retain factory defaults."

};
 
﻿var SoftNoticeDes = 
{ 
	s2001:      "On this page, you can view the open source software notice.",
	s2002:      "OPEN SOURCE SOFTWARE NOTICE",
	s2003:      "This document contains an open source software notice for this product. The open source software licenses are granted by the respective right holders. And the open source licenses prevails all other license information with regard to the respective open source software contained in the product.",
	s2004:      "Warranty Disclaimer",
	s2005:      "THE OPEN SOURCE SOFTWARE IN THIS PRODUCT IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE APPLICABLE LICENSES FOR MORE DETAILS.",
	s2006:      "Open Source Software Information",
	s2007:      "Software",
	s2008:      "Version",
	s2009:      "Copyright Notice",
	s2010:      "License",
	s2011:      "License Link",
	s2012:      "Written Offer",
	s2013:      "This product contains software whose rights holders license it on the terms of the GNU General Public License, version 2 (GPLv2) and/or other open source software licenses. We will provide you and any third party with the source code of the software licensed under an open source software license if you send us a written request by mail or email to the following addresses: <br/>foss@huawei.com<br/>detailing the name of the product and the firmware version for which you need the source code and indicating how we can contact you.<br/><br/><span class=copyrightinfo_title_bold>PLEASE NOTE THAT WE WILL ASK YOU TO PAY US FOR THE COSTS OF A DATA CARRIER AND THE POSTAL CHARGES TO SEND THE DATA CARRIER TO YOU. THIS OFFER IS VALID FOR THREE YEARS FROM THE MOMENT WE DISTRIBUTED THE PRODUCT AND VALID FOR AS LONG AS WE OFFER SPARE PARTS OR CUSTOMER SUPPORT FOR THAT PRODUCT MODEL.</span>",
	s2014:      "Open Source Software Notice",
	s2015:      "Return",
	s2017:      "Caution",
	s2018:      "<strong class=\"color_yellow1\">■</strong>Protect the device from ingress of water or other liquids. Dry your hands before connecting or disconnecting cables. Stop the device and switch off the power before connecting or disconnecting cables.",
	s2019:      "<strong class=\"color_yellow1\">■</strong>If an abnormality occurs, for example, liquid inflooding the device, or smoke, an unusual sound, or a smell detected, stop using the device immediately, switch off the power, and disconnect all cables (such as the power cable and network cable) from the device. If the device malfunctions, contact the specified service center.",
	s2020:      "<strong class=\"color_yellow1\">■</strong>Keep the device away from heat sources and any place which is subject to high temperature. Otherwise this may cause breakdown of this product and cable, resulting in fire or electrical shock. Keep the device away from water sources or wet places.",
	s2021:      "<strong class=\"color_yellow1\">■</strong>If the device is mistakenly dropped and fails during using it, switch off the device and disconnect all the cable including power cable, ethernet cable and network cable. Do not install the device in other modes, such as mounting it on the wall or the ceiling.",
	s2022:      "<strong class=\"color_yellow1\">■</strong>The power supply voltage of the device must meet the requirements on the input voltage of the device. Do not use any power adapter that is not in the standard configuration. Otherwise, the device may be abnormal or unsafe.",
	s2023:      "<strong class=\"color_yellow1\">■</strong>The power cable of the device must not be placed too much in one outlet. If many plugs are placed in one outlet, table tap and others may be overheated or destroyed.",
	s2024:      "<strong class=\"color_yellow1\">■</strong>Keep power plugs clean and dry to avoid electric shocks or any other hazards.",
	s2025:      "<strong class=\"color_yellow1\">■</strong>The device is designed to be installed vertically. Do not place the device horizontally. Do not install any object on the device, otherwise the device will be damaged due to overheating or deformation. Reserve a space of at least 10 cm above and around the device for heat dissipation.",
	s20258040H: "<strong class=\"color_yellow1\">■</strong>The device is designed to be installed horizontally. Do not place the device vertically. Do not install any object on the device, otherwise the device will be damaged due to overheating or deformation. Reserve a space of at least 10 cm above and around the device for heat dissipation.",
	s2026:      "<strong class=\"color_yellow1\">■</strong>Prevent foreign objects, such as metal parts, from entering the device through the heat dissipation mesh.",
	s2027:      "<strong class=\"color_yellow1\">■</strong>Protect the outer case of the device from scratches, because the paint that peels off from the scratched areas can cause device abnormalities. If the paint falls into the device, it may cause short circuits. In addition, peeled-off paint can cause allergic reaction to the human body.",
	s2028:      "<strong class=\"color_yellow1\">■</strong>Switch off the power and disconnect all cables, including the power cable, ethernet.",
	s2029:      "<strong class=\"color_yellow1\">■</strong>Keep the device away from electric appliances that generate strong magnetic or electric fi elds, such as microwave ovens, refrigerators, and mobile phones.",
	s2030:      "<strong class=\"color_yellow1\">■</strong>Keep the device out of the reach of children as the components or accessories may be swallowed.",
	s2031:      "Note",
	s2032:      "<strong class=\"color_yellow1\">■</strong>Install the device in strict compliance with the requirements of the supplier.",
	s2033:      "<strong class=\"color_yellow1\">■</strong>The device is a laser product. Do not look directly into the optical port without eye protection.",
	s2034:      "<strong class=\"color_yellow1\">■</strong>For the environmental temperature to use this device, use it within the specification of temperature.",
	s2035:      "<strong class=\"color_yellow1\">■</strong>Disconnect the power cable from the outlet before moving the device. Grip the power plug and disconnect it from the outlet instead of pulling the cable when disconnecting the power cable from the outlet.",
	s2036:      "<strong class=\"color_yellow1\">■</strong>Switch off the power and remove the power plug if the device is not used over a long time.",
	s2037:      "<strong class=\"color_yellow1\">■</strong>Do not stamp, pull, drag, or excessively bend the cables, because they may get damaged. Damaged cables can cause a device failure.",
	s2038:      "<strong class=\"color_yellow1\">■</strong>Do not use the cables that are damaged or aged.",
	s2039:      "<strong class=\"color_yellow1\">■</strong>Do not disassemble the device without permission. If the device malfunctions, contact the specified service center.",
	s2040:      "<strong class=\"color_yellow1\">■</strong>Keep the device away from the dirt.",
	s2041:      "<strong class=\"color_yellow1\">■</strong>Keep the device clean. Use a dry cloth instead of wet cloth to sweep the dirt. Before cleaning the device, stop using the device, switch off the power, and disconnect all cables, including the power cable and network cables, from the device.",
	s2043:      "<strong class=\"color_yellow1\">■</strong>Do not use liquid or spray-on detergent to clean the outer case of the device. Use a dry soft cloth instead.",
	s2044:      "<strong class=\"color_yellow1\">■</strong>Keep the device away form the television and radio which may affect the device.",
	s2045:      "<strong class=\"color_yellow1\">■</strong>If this product is no longer used, contact the specified service center.",
	s2046:      "<strong class=\"color_yellow1\">■</strong>Do not install network cables, power adapters or power adapter cables outdoors. Adopting these measures will help prevent device damage and bodily injuries which are especially prone during thunderstorms.",
	s2047:      "Software information",
	s2048:      "Please refer to <strong class=\"color_bule1\"><a href=\"/html/ssmp/softnotice/opensfnotice.asp\">here</a></strong> for software information about this product.",
	s2049:      "This product contains software whose rights holders license it on the terms of the GNU General Public License, version 2 (GPLv2) and/or other open source software licenses. You and any third party will be provided with the source code of the software licensed under an open source software license if you send a written request by mail or email to the following addresses: <br/>foss@huawei.com<br/>detailing the name of the product and the firmware version for which you need the source code and indicating how you can be contacted.<br/><br/><span class=copyrightinfo_title_bold>PLEASE NOTE THAT YOU WILL BE ASKED TO PAY FOR THE COSTS OF A DATA CARRIER AND THE POSTAL CHARGES TO SEND THE DATA CARRIER TO YOU. THIS OFFER IS VALID FOR THREE YEARS FROM THE MOMENT THE PRODUCT WAS DISTRIBUTED AND VALID FOR AS LONG AS SPARE PARTS OFFERED OR CUSTOMER SUPPORT FOR THAT PRODUCT MODEL.</span>",
	s2050:      "Copyright Notice and License Texts"
}; 
﻿var WebcertmgntLgeDes = 
{ 	
	s0d21:    "Apply",
    s0d22:    "Cancel",
    s0d23:    "Enable Certificate Authentication and Set Private Key Password",
    s0d25:    "Enable Certificate Authentication:",
    s0d26:    "Private Key Password:",
    s0d28:    "Confirm Password:",
    s0d29:    "Import Certificate",
    s0d2a:    "Certificate:",
    s0d2b:    "Browse…",
    s0d2c:    "Import Certificate",
	s0d10:    "Select a file path.",
    s0d11:    "The file path length cannot exceed 128 characters.",
	s0d0f:    "The confirm password is different from the private key password.",
	s0d14:    "Successfully changed the private key password. It takes effect after a device restart.",
	s1430:	  "The password cannot be blank. Please retry.",
	s1116:    "1.The password must contain at least 6 characters.</br>2.The password must contain at least two of the following combinations: </br>&nbsp;&nbsp;&nbsp;Digit, uppercase letter, lowercase letter </br>&nbsp;&nbsp;&nbsp;Special characters (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ? and space).</br>3.The password cannot be any user name or user name in reverse order.",
	s1901:	  "On this page, you can set the SSL authentication password used for accessing an ONT using HTTPS and import the corresponding SSL certificate. ",
	s1902:	  "The password strength is too weak. Configure it again.",
	s1903:	  "SSL Certificate Management",
	s1904:    "The password must consist of 1 to 127 characters.",
	s1905:    "(1–127 characters. This password takes effect after a device restart.)"
};
 
﻿var Tr069LgeDes = 
{ 
	s0100:    "On this page, you can set ACS parameters, set the password for authentication using an SSL certificate, and import the required SSL certificate.",
	s0101:	  "ACS Configuration",
	s1116:    "1.The password must contain at least 6 characters.<br/>2.The password must contain at least two of the following combinations: <br/>&nbsp;&nbsp;&nbsp;Digit, uppercase letter, lowercase letter <br/>&nbsp;&nbsp;&nbsp;Special characters (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ? and space).<br/>3.The password cannot be any user name or user name in reverse order.",
	s1430:	  "The password cannot be blank. Please retry.",
	s1902:	  'The password strength is too weak. Configure it again.',
    s0d01:    "Enter a URL.",
    s0d02:    "The ACS URL cannot contain spaces or the following characters:\"< > \' \" { } [ ] % \\ ^ # |\"",
    s0d03:    "Invalid informing interval.",
    s0d04:    "Invalid informing time.",
    s0d05:    "Enter an ACS user name.",
    s0d06:    "Invalid ACS user name.",
    s0d07:    "Enter the ACS password.",
    s0d08:    "Invalid ACS password.",
    s0d09:    "Enter a connection request user name.",
    s0d0a:    "Invalid connection request user name.",
    s0d0b:    "Enter a connection request password.",
    s0d0c:    "Invalid connection request password.",
    s0d0d:    "Invalid DSCP value.",
    s0d0e:    "The password must consist of 1 to 32 characters.",
    s0d0f:    "The confirm password is different from the private key password.",
    s0d10:    "Select a file path.",
    s0d11:    "The file path length cannot exceed 128 characters.",
    s0d12:    "The file is too large.",
    s0d13:    " is invalid or does not exist.",
    s0d14:    "Successfully changed the private key password. It takes effect after a device restart.",
    s0d15:    "ACS Parameter Settings",
    s0d16:    "If TR069 auto-connection is enabled, you can set the ACS parameters of the terminal.",
    s0d17:    "Enable Periodic Informing:",
    s0d18:    "Informing Interval:",
    s0d19:    "Informing Time:",
    s0d1a:    "yyyy-mm-ddThh:mm:ss (for example, 2009-12-20T12:23:34)",
    s0d1b:    "ACS User Name:",
    s0d1c:    "ACS Password:",
    s0d1d:    "(1–256 characters)",
    s0d1e:    "Connection Request User Name:",
    s0d1f:    "Connection Request Password:",
    s0d20:    "(1–256 characters)",
    s0d21:    "Apply",
    s0d22:    "Cancel",
    s0d23:    "Enable Certificate Authentication and Set Private Key Password",
    s0d24:    "To allow the device to connect to the ACS in SSL mode, you can enable certificate authentication, set the private key password, and import the certificate provided by the carrier.",
    s0d25:    "Enable Certificate Authentication:",
    s0d26:    "Private Key Password:",
    s0d27:    "(1–32 characters. This password takes effect after a device restart.)",
    s0d28:    "Confirm Password:",
    s0d29:    "Import Certificate",
    s0d2a:    "Certificate:",
    s0d2b:    "Browse…",
    s0d2c:    "Import Certificate",
	s0d2d:    "The ACS URL contains an invalid port ID.",
	s0d2e:    "The ACS URL contains non-ASCII characters.",
	s0d2f:    "ACS URL:",
	s0d30:    "DSCP:",
	s0d31:    "The ACS password is too weak. Are you sure you want to continue?",
	s0d32:    "The password in the connection request is too weak. Are you sure you want to continue?",
	s0d33:    "The ACS password and the password in the connection request are too weak. Are you sure you want to continue?",
	s0d34:"[1 - 2147483647](s)",
	s0d35:"(0~63)",
	s0d36:"Enable ACS Management:",
	s1700:"TR-069 Configurations",
	s1701:"This page is used to configure the TR069-CPE. Here you may change the setting for the ACS's parameters.",
	s1702:"ACS:",
	s1703:"Enable:",
	s1704:"URL:",
	s1705:"User Name:",
	s1706:"Password:",
	s1707:"Periodic Inform Enable:",
	s1708:"Periodic Inform Interval:",
	s1709:"Connection Request:",
	s1710:"User Name:",
	s1711:"Password:",
	s1712:"Path:",
	s1713:"Port:",
	s1714:"Apply",
	s1715:"Cancel",
	s1716:"Path",
	s1717:' contains an invalid character "',
	s1718:"Invalid port ID. Enter a number.",
	s1719:"The first character of the port ID cannot be 0."
	
	
};
 
﻿var UsbstatusLgeDes =
{
	s0401:"On this page, you can view the USB device status.",
	s0402:"USB Status:",
	s0403:"Disconnected",
	s0404:"Connected",
	s0405:"USB Status"
};
 
﻿var UsbdevicesLgeDes =
{
	s001:	"File Sharing",
	s002:	"Allow devices like USB Pen-Drives and External HDDs to be shared on your network. <br> To access, type \\vivobox in your file manager.",
	s003:	"Enabled",
	s004:	"Disabled",
	s005:	"Printers",
	s006:	"Allow USB printers to be shared on your network.",
	s007:	"DLNA",
	s008:	"Allow devices like Pen-Drives and External HD connected to the USB port,<br> to share multimedia files with other DLNA devices, such as PCs, TVs and smartphones.",
	s009:	"Cancel",
	s010:	"Save"
};
 
﻿var UsbHostLgeDes =
{
	s1436:    "Browse Directory",
	s1439:    "The password is weak. Continue?",
	s1605:    "Browse...",
	ss1116b:  "1.It is recommended that the password consist of at least six characters.<br/>2. It is suggested that at least two types of the following characters be included in the password: digits, uppercase characters, lowercase characters, and special characters. Special characters can be the following: `~!@#$%^&*()-_=+|[{}];:'&lt;,.&gt;/?<br/>3. It is suggested that the password be not the username or the username in reverse order.",
	s0501:    "Invalid port ID.",
	s0502:    "Invalid port ID. Enter a number ranging from 1 to 65535.",
	s0503:    "Exceeded the length limit of the user name (255 characters).",
	s0504:    "Enter a valid user name.",
	s0505:    "The user name cannot contain any spaces.",
	s0506:    "The password is too long.",
	s0507:    "Invalid password.",
	s0508:    "The path is too long.",
	s0509:    "Invalid path.",
	s050a:    "Invalid FTP URL.",
	s050b:    "The FTP URL cannot contain spaces or the following characters:\"< > \' \" { } [ ] % \\ ^ # |\"",
	s050c:    "Select a USB device.",
	s050d:    "Exceeded the length limit of the user name (256 characters).",
	s050e:    "Enter the user name.",
	s050f:    "Invalid user name.",
	s0510:    "Invalid user name with spaces.",
	s0511:    "Exceeded the length limit of the password (256 characters).",
	s0512:    "The password cannot be left blank.",
	s0513:    "Invalid password.",
	s0514:    "Select a USB device first.",
	s0515:    "Exceeded the length limit of the root path (256 characters).",
	s0516:    "Invalid root path.",
	s0517:    "Changing the configuration will restart the FTP server. Are you sure you want to continue?",
	s0518:    "FTP Client Configuration",
	s0519:    "On this page, you can configure the FTP client to download files from a network to a USB device.",
	s051a:    "Port ID:",
	s051b:    "User Name:",
	s051c:    "Password:",
	s051d:    "USB Device:",
	s051e:    "Path:",
	s051f:    "Download",
	s0520:    "Status",
	s0521:    "FTP Server Configuration",
	s0522:    "On this page, you can configure the FTP server to share data on the USB device with devices on the LAN.",
	s0523:    "Enable LAN-side or WAN-side access to the ONT through FTP, and select the UTF-8 mode.",
	s0524:    "Enable FTP Server:",
	s0525:    "Root Path:",
	s0526:    "Apply",
	s0527:    "Cancel",
	s0528:    "User Name",
	s0529:    "Password",
	s052a:    "Port ID",
	s052b:    "Path",
	s052c:    "The password cannot start with a space.",
	s052d:    "The password cannot end with a space.",
	s052e:    "No USB Device",
	s052f:    "FTP URL:",
	s0530:    "FTP URL",
	s0531:    "Caution:",
	s0532:    "Do not remove and re-insert the USB storage device in use, because this may damage files in it.",
	s0533:    "This file already exists on the USB storage device. Are you sure you want to replace it?",
	s0534:    "The FTP URL address cannot contain the following characters: \"<, >, \', \", {, }, [, ], \\, ^, #, |\".",
	s0535:    "(/example: test/test.txt)",
	s0536:    "On this page, you can configure the FTP client for file downloading from to a storage device of the home gateway, and configure the FTP server for resource sharing.",
	s0537:    "<strong class=\"color_red\">When configuring the FTP server, enable the LAN-side or WAN-side FTP function and select character code in UTF-8 format.</strong>",
	s0538:    "FTP Configuration",
	s0539:    "On this page, you can configure the FTP client for file downloading from to a storage device of the home gateway, and configure the FTP server for resource sharing. <br> When configuring the FTP server, enable the LAN-side or WAN-side FTP function and select character code in UTF-8 format.<br>Caution:<br>Do not remove and re-insert the USB storage device in use, because this may damage files in it.",
	s0540:	  "The USB device is in read-only mode and no data can be written. ",
	s0541:	  "The SD card is in read-only mode and no data can be written. ",
	s0542:	  "The storage device is in read-only mode and no data can be written. ",	
	s0543:    "The configured port conflicts with the internal service port.",
	s0544:    "The configured port conflicts with the port of the port mapping service.",
	s0545:    "The configured port conflicts with the port of the port trigger service.",
	s0546:    "The configured port conflicts with the voice service port.",
	s0547:    "The configured port conflicts with the FTP service port.",
	s0548:    "Remove USB Devices",
	s0549:    "On this page, you can remove your connected USB devices.",
	s0550:    "Remove USB Devices",
	s0551:    "Remove",
	s0552:    "Update",
	s0553:    "Are you sure you want to remove it?",
	s0554:    "The selected USB device is not connected or is removed.",
	s0555:    "The removed USB device can be identified only after being removed and inserted.<br>Data may be lost if the USB device to be removed has data being read or written."
};
 
﻿var LogviewLgeDes =
{
	s0100:    "On this page, you can configure, download, and query user logs.",
	s0100a:   "On this page, you can download and query user logs.",
	s0101:    "User Log",
	s1613:    "View Logs",
	s1614:    "You can view log information in the box below.",
	s0b01:    "Enable Filter and Set the Filter Level",
	s0b02:    "On this page, you can specify whether to save logs and set the log level (the logs at this and higher levels will be saved).",
	s0b03:    "Save Log:",
	s0b04:    "Log Level:",
	s0b05:    "Fatal",
	s0b06:    "Critical",
	s0b07:    "Major",
	s0b08:    "Error",
	s0b09:    "Warning",
	s0b0a:    "Notice",
	s0b0b:    "Information",
	s0b0c:    "Debug",
	s0b0d:    "Apply",
	s0b0e:    "Cancel",
	s0b0f:    "Download and View Logs",
	s0b10:    "You can view logs and download log files.",
	s0b11:    "Download Log File",
	s0b12:    "Enable Log Saving",
	s0b13:    "On this page, you can specify whether to save logs.",
	s0b14:    "Log Type:",
	s0b15:    "Config-Log",
	s0b16:    "Shell-Log",
	s0b17:    "Alarm-Log",
	s0b18:    "All-Log",
	s0b19:    "Upload Log File To Remote Server",
	s0b20:    "Upload Enable",
	s0b21:    "Upload Interval",
	s0b22:    "Upload URL",
	s0b23:    "UserName",
	s0b24:    "Password"
};
 
